# Generated by Django 2.1.3 on 2019-07-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chemistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thai_name', models.CharField(max_length=100)),
                ('chem_name', models.CharField(max_length=100)),
                ('another_name', models.CharField(max_length=100)),
                ('explanation', models.TextField()),
                ('cas_registry', models.IntegerField()),
                ('rtecs_number', models.TextField()),
                ('chemical_formula', models.TextField()),
                ('volume', models.FloatField()),
                ('melting_point', models.FloatField()),
                ('category', models.CharField(choices=[('ของแข็ง', 'ของแข็ง'), ('ของเหลว', 'ของเหลว'), ('ก๊าซ', 'ก๊าซ')], max_length=50)),
                ('keep', models.TextField()),
                ('density', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
