# Generated by Django 2.1.3 on 2019-07-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190725_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemistry',
            name='chemical_formula',
            field=models.CharField(max_length=50),
        ),
    ]
