# Generated by Django 2.1.3 on 2019-07-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190725_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemistry',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
