# Generated by Django 2.1.3 on 2019-07-31 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20190725_2348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chemistry',
            old_name='chemical_formula',
            new_name='book_number',
        ),
        migrations.RenameField(
            model_name='chemistry',
            old_name='destroy',
            new_name='chemical_properties',
        ),
        migrations.RenameField(
            model_name='chemistry',
            old_name='another_name',
            new_name='course_number',
        ),
        migrations.RenameField(
            model_name='chemistry',
            old_name='rtecs_number',
            new_name='experiment_number',
        ),
        migrations.RenameField(
            model_name='chemistry',
            old_name='explanation',
            new_name='reactions',
        ),
        migrations.RenameField(
            model_name='chemistry',
            old_name='chem_name',
            new_name='w',
        ),
        migrations.RenameField(
            model_name='chemistry',
            old_name='thai_name',
            new_name='w1',
        ),
        migrations.RemoveField(
            model_name='chemistry',
            name='cas_registry',
        ),
        migrations.RemoveField(
            model_name='chemistry',
            name='category',
        ),
        migrations.RemoveField(
            model_name='chemistry',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='chemistry',
            name='density',
        ),
        migrations.RemoveField(
            model_name='chemistry',
            name='keep',
        ),
        migrations.RemoveField(
            model_name='chemistry',
            name='melting_point',
        ),
        migrations.RemoveField(
            model_name='chemistry',
            name='volume',
        ),
        migrations.AddField(
            model_name='chemistry',
            name='chemical_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chemistry',
            name='course',
            field=models.CharField(choices=[('เคมี', 'เคมี'), ('ชีววิทยา', 'ชีววิทยา')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chemistry',
            name='experiment_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chemistry',
            name='ghs_sign',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='chemistry',
            name='titile',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chemistry',
            name='w2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chemistry',
            name='w3',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chemistry',
            name='w4',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chemistry',
            name='w5',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chemistry',
            name='w6',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chemistry',
            name='w7',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
