# Generated by Django 2.1.3 on 2019-07-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20190731_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemistry',
            name='ghs_sign',
            field=models.ImageField(blank=True, upload_to='GHS_SIGN/%Y/%m/%d'),
        ),
    ]
